create table if not exists batches (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  batch_no text not null,
  received_date date,
  mfg_date date,
  expiry_date date not null,
  quantity_received numeric(10,2) not null default 0,
  quantity_remaining numeric(10,2) not null default 0,
  location_id bigint references locations(id) on delete set null,
  supplier_id bigint references suppliers(id) on delete set null,
  status text,
  note text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- important index for FEFO
create index if not exists idx_batches_expiry on batches(expiry_date);
create index if not exists idx_batches_product on batches(product_id);
create index if not exists idx_batches_location on batches(location_id);