create table if not exists stock_movements (
  id bigint generated by default as identity primary key,
  batch_id bigint references batches(id) on delete cascade,
  product_id bigint references products(id) on delete cascade,
  movement_type text not null, -- IN / OUT / TRANSFER / DISPOSAL
  quantity numeric(10,2) not null,
  movement_date timestamp with time zone default now(),
  source_location_id bigint references locations(id),
  destination_location_id bigint references locations(id),
  reference_no text,
  note text,
  created_at timestamp with time zone default now()
);

create index if not exists idx_movements_batch on stock_movements(batch_id);
create index if not exists idx_movements_product on stock_movements(product_id);