create table if not exists alerts (
  id bigint generated by default as identity primary key,
  batch_id bigint references batches(id) on delete cascade,
  alert_type text not null, -- expired / warning / urgent
  is_read boolean default false,
  action_taken text,
  action_note text,
  created_at timestamp with time zone default now()
);

create index if not exists idx_alerts_batch on alerts(batch_id);